version: '3'
services:
  docker_monitor:
    env_file: ".env.${ENV:?err}"
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m docker_monitor
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
